Update Nexus Core to latest

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -41,47 +41,42 @@ jobs:
         with:
           version: v2.12.2
 
-      - name: Launch Compose Stack
-        run: |
-          docker compose up --quiet-pull -d
+      - name: Setup integration tests
+        run: just up
 
-      - name: Get Compose Logs
-        if: always()
-        run: docker compose logs
-          
       - name: Test
         env:
           APPLICATION_ENVIRONMENT: units
-        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
+          SCYLLA_STORE_LOCAL_ONLY: 1
+        run: just test-all
         
       - name: Visualise Coverage
         if: ${{ github.ref != 'refs/heads/main' && always() }}
         run: go tool cover -html=cover.out -o=cover.html
         
-      - name: Upload Coverage
-        if: ${{ github.ref != 'refs/heads/main' && always() }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage
-          path: cover.html
-          retention-days: 1
-        id: cover
-          
-      - name: Post Coverage
-        if: ${{ github.ref != 'refs/heads/main' && always() }}
-        uses: peter-evans/create-or-update-comment@v4
-        with:
-          issue-number: ${{ github.event.number }}
-          body: |
-            New [coverage report](${{ steps.cover.outputs.artifact-url }}) available :sparkles:
-
       - name: Check Coverage
+        id: coverage
         uses: vladopajic/go-test-coverage@v2
+        continue-on-error: true # Should fail after coverage comment is posted
         with:
           config: ./.testcoverage.yml
-
           ## badge is created and committed only for main branch
           git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
           ## name of branch where badges are stored
           ## ideally this should be orphan branch (see below how to create this branch)
           git-branch: badges
+
+      - name: Post coverage report
+        uses: thollander/actions-comment-pull-request@v3
+        if: ${{ github.ref_name != 'main' }}
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          comment-tag: coverage-report
+          message: |
+            go-test-coverage report:
+            ```${{ fromJSON(steps.coverage.outputs.report) }}```
+
+      - name: Finally check coverage
+        if: steps.coverage.outcome == 'failure'
+        shell: bash
+        run: echo "coverage check failed" && exit 1
